-- USER
CREATE TABLE `USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `USER_username_key` (`username`),
  UNIQUE KEY `USER_email_key` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- INTERSECTION
CREATE TABLE `INTERSECTION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `sector` INT NOT NULL,
  `lat` DOUBLE,
  `lng` DOUBLE,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- SEMAPHOR
CREATE TABLE `SEMAPHOR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `sense` VARCHAR(255) NOT NULL,
  `intersectionId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `SEMAPHOR_intersectionId_idx` (`intersectionId`),
  CONSTRAINT `SEMAPHOR_intersectionId_fkey`
    FOREIGN KEY (`intersectionId`) REFERENCES `INTERSECTION` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- BUS_STATION
CREATE TABLE `BUS_STATION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `sense` VARCHAR(255) NOT NULL,
  `no_people` INT NOT NULL,
  `no_buses` INT NOT NULL,
  `intersectionId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `BUS_STATION_intersectionId_idx` (`intersectionId`),
  CONSTRAINT `BUS_STATION_intersectionId_fkey`
    FOREIGN KEY (`intersectionId`) REFERENCES `INTERSECTION` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TRAM_STATION
CREATE TABLE `TRAM_STATION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `sense` VARCHAR(255) NOT NULL,
  `no_people` INT NOT NULL,
  `no_trams` INT NOT NULL,
  `intersectionId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `TRAM_STATION_intersectionId_idx` (`intersectionId`),
  CONSTRAINT `TRAM_STATION_intersectionId_fkey`
    FOREIGN KEY (`intersectionId`) REFERENCES `INTERSECTION` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TROLEIBUS_STATION
CREATE TABLE `TROLEIBUS_STATION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `sense` VARCHAR(255) NOT NULL,
  `no_people` INT NOT NULL,
  `no_troleibuses` INT NOT NULL,
  `intersectionId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `TROLEIBUS_STATION_intersectionId_idx` (`intersectionId`),
  CONSTRAINT `TROLEIBUS_STATION_intersectionId_fkey`
    FOREIGN KEY (`intersectionId`) REFERENCES `INTERSECTION` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CAR
CREATE TABLE `CAR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(255) NOT NULL,
  `regNr` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `CAR_regNr_key` (`regNr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- BUS
CREATE TABLE `BUS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `regNr` VARCHAR(255) NOT NULL,
  `line` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `BUS_regNr_key` (`regNr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TRAM
CREATE TABLE `TRAM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `regNr` VARCHAR(255) NOT NULL,
  `line` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `TRAM_regNr_key` (`regNr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TROLEIBUS
CREATE TABLE `TROLEIBUS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `regNr` VARCHAR(255) NOT NULL,
  `line` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `TROLEIBUS_regNr_key` (`regNr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- PERSON
CREATE TABLE `PERSON` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CROSSING_CAR
CREATE TABLE `CROSSING_CAR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `speed` DOUBLE,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `semaphorId` INT NOT NULL,
  `carId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `CROSSING_CAR_semaphorId_idx` (`semaphorId`),
  KEY `CROSSING_CAR_carId_idx` (`carId`),
  CONSTRAINT `CROSSING_CAR_semaphorId_fkey`
    FOREIGN KEY (`semaphorId`) REFERENCES `SEMAPHOR` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CROSSING_CAR_carId_fkey`
    FOREIGN KEY (`carId`) REFERENCES `CAR` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CROSSING_BUS
CREATE TABLE `CROSSING_BUS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `speed` DOUBLE,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `semaphorId` INT NOT NULL,
  `busId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `CROSSING_BUS_semaphorId_idx` (`semaphorId`),
  KEY `CROSSING_BUS_busId_idx` (`busId`),
  CONSTRAINT `CROSSING_BUS_semaphorId_fkey`
    FOREIGN KEY (`semaphorId`) REFERENCES `SEMAPHOR` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CROSSING_BUS_busId_fkey`
    FOREIGN KEY (`busId`) REFERENCES `BUS` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CROSSING_TRAM
CREATE TABLE `CROSSING_TRAM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `speed` DOUBLE,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `semaphorId` INT NOT NULL,
  `tramId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `CROSSING_TRAM_semaphorId_idx` (`semaphorId`),
  KEY `CROSSING_TRAM_tramId_idx` (`tramId`),
  CONSTRAINT `CROSSING_TRAM_semaphorId_fkey`
    FOREIGN KEY (`semaphorId`) REFERENCES `SEMAPHOR` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CROSSING_TRAM_tramId_fkey`
    FOREIGN KEY (`tramId`) REFERENCES `TRAM` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CROSSING_TROLEIBUS
CREATE TABLE `CROSSING_TROLEIBUS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `speed` DOUBLE,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `semaphorId` INT NOT NULL,
  `troleibusId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `CROSSING_TROLEIBUS_semaphorId_idx` (`semaphorId`),
  KEY `CROSSING_TROLEIBUS_troleibusId_idx` (`troleibusId`),
  CONSTRAINT `CROSSING_TROLEIBUS_semaphorId_fkey`
    FOREIGN KEY (`semaphorId`) REFERENCES `SEMAPHOR` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CROSSING_TROLEIBUS_troleibusId_fkey`
    FOREIGN KEY (`troleibusId`) REFERENCES `TROLEIBUS` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CROSSING_PERSON
CREATE TABLE `CROSSING_PERSON` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `semaphorId` INT NOT NULL,
  `personId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `CROSSING_PERSON_semaphorId_idx` (`semaphorId`),
  KEY `CROSSING_PERSON_personId_idx` (`personId`),
  CONSTRAINT `CROSSING_PERSON_semaphorId_fkey`
    FOREIGN KEY (`semaphorId`) REFERENCES `SEMAPHOR` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CROSSING_PERSON_personId_fkey`
    FOREIGN KEY (`personId`) REFERENCES `PERSON` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- STOPPED_BUS
CREATE TABLE `STOPPED_BUS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stoppedMinutes` INT NOT NULL,
  `expectedArrival` TIMESTAMP NOT NULL,
  `actualArrival` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `busId` INT NOT NULL,
  `stationId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `STOPPED_BUS_busId_idx` (`busId`),
  KEY `STOPPED_BUS_stationId_idx` (`stationId`),
  CONSTRAINT `STOPPED_BUS_busId_fkey`
    FOREIGN KEY (`busId`) REFERENCES `BUS` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `STOPPED_BUS_stationId_fkey`
    FOREIGN KEY (`stationId`) REFERENCES `BUS_STATION` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- STOPPED_TRAM
CREATE TABLE `STOPPED_TRAM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stoppedMinutes` INT NOT NULL,
  `expectedArrival` TIMESTAMP NOT NULL,
  `actualArrival` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tramId` INT NOT NULL,
  `stationId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `STOPPED_TRAM_tramId_idx` (`tramId`),
  KEY `STOPPED_TRAM_stationId_idx` (`stationId`),
  CONSTRAINT `STOPPED_TRAM_tramId_fkey`
    FOREIGN KEY (`tramId`) REFERENCES `TRAM` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `STOPPED_TRAM_stationId_fkey`
    FOREIGN KEY (`stationId`) REFERENCES `TRAM_STATION` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- STOPPED_TROLEIBUS
CREATE TABLE `STOPPED_TROLEIBUS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stoppedMinutes` INT NOT NULL,
  `expectedArrival` TIMESTAMP NOT NULL,
  `actualArrival` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `troleibusId` INT NOT NULL,
  `stationId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `STOPPED_TROLEIBUS_troleibusId_idx` (`troleibusId`),
  KEY `STOPPED_TROLEIBUS_stationId_idx` (`stationId`),
  CONSTRAINT `STOPPED_TROLEIBUS_troleibusId_fkey`
    FOREIGN KEY (`troleibusId`) REFERENCES `TROLEIBUS` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `STOPPED_TROLEIBUS_stationId_fkey`
    FOREIGN KEY (`stationId`) REFERENCES `TROLEIBUS_STATION` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CHANGING
CREATE TABLE `CHANGING` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(255) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `semaphorId` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `CHANGING_semaphorId_idx` (`semaphorId`),
  CONSTRAINT `CHANGING_semaphorId_fkey`
    FOREIGN KEY (`semaphorId`) REFERENCES `SEMAPHOR` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;